-- Run this once in Supabase SQL Editor to enable the new book metadata columns
ALTER TABLE IF EXISTS books
  ADD COLUMN IF NOT EXISTS date_received DATE,
  ADD COLUMN IF NOT EXISTS ddc_no VARCHAR(100),
  ADD COLUMN IF NOT EXISTS edition VARCHAR(100),
  ADD COLUMN IF NOT EXISTS volumes VARCHAR(100),
  ADD COLUMN IF NOT EXISTS pages VARCHAR(100),
  ADD COLUMN IF NOT EXISTS source_of_fund VARCHAR(255),
  ADD COLUMN IF NOT EXISTS price NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS publisher VARCHAR(255),
  ADD COLUMN IF NOT EXISTS remarks TEXT;
